name: boono_mobile
description: A new Flutter project.

dependencies:
  # SQLite
  sqflite: 0.11.0
  # Httpリクエストを送るため
  http: ^0.11.3
  rxdart: any
  # ファイルパスと取得するため
  path_provider: any
  # Push通知を受け取るため
  firebase_messaging: 1.0.3
  # テータを格納するためのやつ
  shared_preferences: 0.4.2
  #テスト用のモック
  mockito: any

  collection: any

  # Theme切り替えのため
  dynamic_theme:
      git:
        url: git://github.com/Norbert515/dynamic_theme.git

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#00000000"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/now-loading.png
    - assets/icon/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
