version: 2
jobs:
  build:
    environment:
      - LANG: en_US.UTF-8
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: Install Flutter SDK
          command: git clone -b v0.10.1 https://github.com/flutter/flutter.git ~/flutter
      - run:
          name: Flutter packages get
          command: ~/flutter/bin/flutter packages get
      - run:
          name: run Lint
          command: ~/flutter/bin/flutter analyze
      - run:
          name: run tests
          command: ~/flutter/bin/flutter test --coverage --coverage-path=lcov.info && bash <(curl -s https://codecov.io/bash)
